HTTPD=${HTTPD:-"nginx"}
FPM=${FPM:-"fpm"}

SOCKDIR=${SOCKDIR:-"/tmp/sockets"}
SOCKDIR_PERM=${SOCKDIR_PERM:-"3730"}
SOCKDIR_GROUP=${SOCKDIR_GROUP:-$HTTPD}

BACKDIR=${BACKDIR:-"/tmp/backs"}
BACKDIR_PERM=${BACKDIR_PERM:-"3733"}
BACKDIR_GROUP=${BACKDIR_GROUP:-$FPM}

SHIMDIR=${SHIMDIR:-"/tmp/shims"}
SHIMDIR_PERM=${SHIMDIR_PERM:-"3733"}
SHIMDIR_GROUP=${SHIMDIR_GROUP:-$FPM}

WEBDIR=${WEBDIR:-"/tmp/website"}
WEBDIR_PERM=${WEBDIR_PERM:-"3711"}
WEBDIR_GROUP=${WEBDIR_GROUP:-$HTTPD}

CONFIGDIR=${CONFIGDIR:-"/tmp/config"}
CONFIGDIR_PERM=${CONFIGDIR_PERM:-"755"}
CONFIGDIR_GROUP=${CONFIGDIR_GROUP:-$HTTPD}

